# This workflow will do a clean install of node dependencies, build the source code and run tests

name: Node.js Build CI

on:
  push:
    branches:
      - main
  pull_request:
    branches: 
      - main 

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v2
    - name: Use Node.js
      uses: actions/setup-node@v1
      with:
        node-version: '10.x'
    - name: Run Npm install
      run: npm ci
    - name: Run npm Build
      run: npm run build --if-present
      
  test:
    needs: build
    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v2
    - name: Use Node.js
      uses: actions/setup-node@v1
      with:
        node-version: '10.x'
    - name: Run npm Tests
      run: npm run test --if-present
    
  lint:
    needs: build
    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v2
    - name: Use Node.js
      uses: actions/setup-node@v1
      with:
        node-version: '10.x'

    - name: Run npm Lint
      run: npm run lint --if-present