# This workflow will do a clean install of node dependencies, build the source code and run tests across different versions of node
# For more information see: https://help.github.com/actions/language-and-framework-guides/using-nodejs-with-github-actions

name: Node.js Release CI

on:
  push:
    branches: 
      - main

jobs:
  release_increment:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v2
    - uses: actions/setup-node@v1
      with:
        node-version: '10.x'

    - name: Determine Type of Version Increment
      id: inctype
      run: |
        PATCH_INC=$(git log --oneline -1 | { grep patch/ || :; })
        echo "::set-output name=PATCH_INC::$PATCH_INC"
        echo $PATCH_INC
        MINOR_INC=$(git log --oneline -1 | { grep minor/ || :; })
        echo "::set-output name=MINOR_INC::$MINOR_INC"
        echo $MINOR_INC
        MAJOR_INC=$(git log --oneline -1 | { grep major/ || :; })
        echo "::set-output name=MAJOR_INC::$MAJOR_INC"
        echo $MAJOR_INC
        
    - name: Patch Increment of Project Version
      if: steps.inctype.outputs.PATCH_INC == 1
      run: |
        git config user.name $GITHUB_ACTOR
        git config user.email gh-actions-${GITHUB_ACTOR}@github.com 
        npm version patch
        git remote add gh-origin https://${GITHUB_ACTOR}:${{secrets.GITHUB_TOKEN}}@github.com/${GITHUB_REPOSITORY}.git
        git push gh-origin HEAD:main --tags

    - name: Minor Increment of Project Version
      if: steps.inctype.outputs.MINOR_INC == 1
      run: |
        git config user.name $GITHUB_ACTOR
        git config user.email gh-actions-${GITHUB_ACTOR}@github.com 
        npm version minor
        git remote add gh-origin https://${GITHUB_ACTOR}:${{secrets.GITHUB_TOKEN}}@github.com/${GITHUB_REPOSITORY}.git
        git push gh-origin HEAD:main --tags

    - name: Major Increment of Project Version
      if: steps.inctype.outputs.MAJOR_INC == 1
      run: |
        git config user.name $GITHUB_ACTOR
        git config user.email gh-actions-${GITHUB_ACTOR}@github.com 
        npm version major
        git remote add gh-origin https://${GITHUB_ACTOR}:${{secrets.GITHUB_TOKEN}}@github.com/${GITHUB_REPOSITORY}.git
        git push gh-origin HEAD:main --tags